version: "3.9"

services:
  todo-service:
    build:
      context: .
      dockerfile: FlaskContainerfile
      args:
        SERVICE_NAME: todo
    ports:
      - "5001:5000"    # 5001 on host maps to 5000 in container
    volumes: # Attach a volume so code changes reflect immediately
      - ./backend/todo:/app
    networks:
      - todo-network


  user-service:
    build:
      context: .
      dockerfile: FlaskContainerfile
      args:
        SERVICE_NAME: user
    ports:
      - "5002:5000"    # 5002 on host maps to 5000 in container
    volumes:  # Attach a volume so code changes reflect immediately
      - ./backend/user:/app
    networks:
      - todo-network


  nginx:
    build:
      context: .
      dockerfile: NginxContainerfile    
    ports:
      - "5003:80"  # Nginx port
    depends_on:
      - user-service
      - todo-service
    networks:
      - todo-network


  postgres:
    build:
      context: .
      dockerfile: PostgresContainerfile
    container_name: todo-postgres
    shm_size: 256mb
    env_file:
      - postgres.env
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432" #15432 on host maps to 5432 in container
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  pgdata: